### ISSUE TITLE
@sortkey not working

### ISSUE THREAD

**Issue by ferrall** [yozw/oxdoc#8] opened 2014-07-07 16:50 UTC
The sortkey option no longer seems to work as before.

It seems like it has some effect on the order of files, but the ordering on the command line also matters even when both source files include a sortkey.

It also seems to matter whether the sortkey appears in .oxdoc (indirectly read) or appears in the file listed on the command line (not Ox files).

**Comment by yozw** [comment] 2023-08-09 19:14
If this is still an issue, can you produce a minimal example, and describe intended behaviour? I'm not entirely sure what you expect here.

**Comment by yozw** [comment] 2023-08-09 20:24
Fixed in https://github.com/yozw/oxdoc/commit/388890bd933166deecd3859e1000c42063e7a27a

**Closed by yozw** 2023-08-09 20:24 UTC
